# -*- coding: utf-8 -*-
"""Dual RigidBody Pendulum Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgxv9IbJWruQbxK3MV4AsRDiF7b4WKCW

# Dual RigidBody Pendulum Simulation

## 定義
- 原点 $O$、物体1の重心 $G_1$、物体2の重心 $G_2$、物体1と物体2の接続点 $P$
- $OG_1$ の長さ $r_1$、$PG_2$ の長さ $r_2$、$OP$ の長さ $l$
- $OG_1$ と鉛直（下向き）との角度差 $\theta_1$、$OG_1$ と $OP$ の角度差 $\alpha$、$PG_2$ と鉛直（下向き）との角度差 $\theta_2$
- 角速度 $\omega_1=\dot{\theta}_1$、$\omega_2=\dot{\theta}_2$
- 質量 $m_1,m_2$
- 重心まわり（回転軸まわり）の慣性モーメント $I_1,I_2$
- 重力加速度 $g$
- 以後，$\alpha$ は定数（$\dot{\alpha}=0$）とする

---

## 基本式の導出

### 重心 $G_1$
$$
r_{G_1}=
\begin{bmatrix}
x_{G_1}\\
y_{G_1}
\end{bmatrix}
=
r_1
\begin{bmatrix}
\sin\theta_1\\
-\cos\theta_1
\end{bmatrix}
$$

### 接続点 $P$
$$
r_{P}=
\begin{bmatrix}
x_{P}\\
y_{P}
\end{bmatrix}
=
l
\begin{bmatrix}
\sin(\theta_1+\alpha)\\
-\cos(\theta_1+\alpha)
\end{bmatrix}
$$

### 重心 $G_2$
$$
r_{G_2}=r_P+
r_2
\begin{bmatrix}
\sin\theta_2\\
-\cos\theta_2
\end{bmatrix}
=
l
\begin{bmatrix}
\sin(\theta_1+\alpha)\\
-\cos(\theta_1+\alpha)
\end{bmatrix}
+
r_2
\begin{bmatrix}
\sin\theta_2\\
-\cos\theta_2
\end{bmatrix}
$$

---

## 速度（時間微分）

### 重心 $G_1$
$$
\dot r_{G_1}
=
r_1\dot\theta_1
\begin{bmatrix}
\cos\theta_1\\
\sin\theta_1
\end{bmatrix}
\quad\Rightarrow\quad
v_{G_1}^2
=
r_1^2\dot\theta_1^2
$$

### 重心 $G_2$
$$
\dot r_{G_2}
=
l\dot\theta_1
\begin{bmatrix}
\cos(\theta_1+\alpha)\\
\sin(\theta_1+\alpha)
\end{bmatrix}
+
r_2\dot\theta_2
\begin{bmatrix}
\cos\theta_2\\
\sin\theta_2
\end{bmatrix}
$$

内積を取ると
$$
v_{G_2}^2
=
l^2\dot\theta_1^2
+r_2^2\dot\theta_2^2
+2lr_2\dot\theta_1\dot\theta_2\cos(\theta_1+\alpha-\theta_2)
$$

---

## エネルギーの導出

### 剛体の運動エネルギー（一般式）
$$
K=\frac12 mv_G^2+\frac12 I\omega^2
$$

### 物体1の運動エネルギー $K_1$
$$
\begin{aligned}
K_1
&=
\frac12 m_1 v_{G_1}^2+\frac12 I_1\dot\theta_1^2
=
\frac12 m_1(r_1^2\dot\theta_1^2)+\frac12 I_1\dot\theta_1^2 \\
&=
\frac12\left(m_1r_1^2+I_1\right)\dot\theta_1^2
\end{aligned}
$$

### 物体2の運動エネルギー $K_2$
$$
\begin{aligned}
K_2
&=
\frac12 m_2 v_{G_2}^2+\frac12 I_2\dot\theta_2^2 \\
&=
\frac12 m_2\left(
l^2\dot\theta_1^2
+r_2^2\dot\theta_2^2
+2lr_2\dot\theta_1\dot\theta_2\cos(\theta_1+\alpha-\theta_2)
\right)
+\frac12 I_2\dot\theta_2^2
\end{aligned}
$$

### トータルの運動エネルギー $K$
$$
\begin{aligned}
K
&=K_1+K_2 \\
&=
\frac12\left(m_1r_1^2+m_2l^2+I_1\right)\dot\theta_1^2
+\frac12\left(m_2r_2^2+I_2\right)\dot\theta_2^2
+m_2lr_2\,\dot\theta_1\dot\theta_2\cos(\theta_1+\alpha-\theta_2)
\end{aligned}
$$

---

## 位置エネルギーの導出

座標系は $y$ 軸を上向きではなく下向きを正としているため，
$$
U=-mgy
$$
を用いる。

- $y_{G_1}=-r_1\cos\theta_1$
- $y_{G_2}=-l\cos(\theta_1+\alpha)-r_2\cos\theta_2$

### 物体1のポテンシャルエネルギー $U_1$
$$
U_1=-m_1gy_{G_1}
=-m_1g(-r_1\cos\theta_1)
= m_1gr_1\cos\theta_1
$$

### 物体2のポテンシャルエネルギー $U_2$
$$
\begin{aligned}
U_2
&=-m_2gy_{G_2}
=-m_2g\left(-l\cos(\theta_1+\alpha)-r_2\cos\theta_2\right) \\
&= m_2g\left(l\cos(\theta_1+\alpha)+r_2\cos\theta_2\right)
\end{aligned}
$$

### トータルの位置エネルギー $U$
$$
U
=U_1+U_2
=
m_1gr_1\cos\theta_1
+m_2g\left(l\cos(\theta_1+\alpha)+r_2\cos\theta_2\right)
$$

---

## ラグランジュアン（ラグランジュ関数） $L=K-U$

$$
\begin{aligned}
L
&=K-U \\
&=
\frac12\left(m_1r_1^2+m_2l^2+I_1\right)\dot\theta_1^2
+\frac12\left(m_2r_2^2+I_2\right)\dot\theta_2^2
+m_2lr_2\,\dot\theta_1\dot\theta_2\cos(\theta_1+\alpha-\theta_2) \\
&\quad
-\left[
m_1gr_1\cos\theta_1
+m_2g\left(l\cos(\theta_1+\alpha)+r_2\cos\theta_2\right)
\right]
\end{aligned}
$$

---

## 偏微分の計算

以後，
$$
\Delta=\theta_1+\alpha-\theta_2
$$
とおく。

### (1) $\frac{\partial L}{\partial \theta_1}$
$$
\frac{\partial L}{\partial \theta_1}
=
- m_2lr_2\,\dot\theta_1\dot\theta_2\sin\Delta
+ m_1gr_1\sin\theta_1
+ m_2gl\sin(\theta_1+\alpha)
$$

### (2) $\frac{\partial L}{\partial \theta_2}$
$$
\frac{\partial L}{\partial \theta_2}
=
+ m_2lr_2\,\dot\theta_1\dot\theta_2\sin\Delta
+ m_2gr_2\sin\theta_2
$$

### (3) $\frac{\partial L}{\partial \dot{\theta}_1}$
$$
\frac{\partial L}{\partial \dot{\theta}_1}
=
\left(m_1r_1^2+m_2l^2+I_1\right)\dot\theta_1
+m_2lr_2\,\dot\theta_2\cos\Delta
$$

### (4) $\frac{\partial L}{\partial \dot{\theta}_2}$
$$
\frac{\partial L}{\partial \dot{\theta}_2}
=
\left(m_2r_2^2+I_2\right)\dot\theta_2
+m_2lr_2\,\dot\theta_1\cos\Delta
$$

### (5) $\frac{d}{dt}\frac{\partial L}{\partial \dot{\theta}_1}$
$$
\begin{aligned}
\frac{d}{dt}\frac{\partial L}{\partial \dot{\theta}_1}
&=
\left(m_1r_1^2+m_2l^2+I_1\right)\ddot\theta_1
+m_2lr_2\cos\Delta\,\ddot\theta_2 \\
&\quad
- m_2lr_2\,\dot\theta_2(\dot\theta_1-\dot\theta_2)\sin\Delta
\end{aligned}
$$

### (6) $\frac{d}{dt}\frac{\partial L}{\partial \dot{\theta}_2}$
$$
\begin{aligned}
\frac{d}{dt}\frac{\partial L}{\partial \dot{\theta}_2}
&=
m_2lr_2\cos\Delta\,\ddot\theta_1
+\left(m_2r_2^2+I_2\right)\ddot\theta_2 \\
&\quad
+ m_2lr_2\,\dot\theta_1(\dot\theta_1-\dot\theta_2)\sin\Delta
\end{aligned}
$$

---

## ラグランジュ方程式（2階微分方程式）

$$
\frac{d}{dt}\left(\frac{\partial L}{\partial \dot\theta_i}\right)
-\frac{\partial L}{\partial \theta_i}=0
\qquad (i=1,2)
$$

よって

$$
\begin{aligned}
\left(m_1r_1^2+m_2l^2+I_1\right)\ddot\theta_1
+m_2lr_2\cos\Delta\,\ddot\theta_2
&=
- m_1gr_1\sin\theta_1
- m_2gl\sin(\theta_1+\alpha)
- m_2lr_2\,\dot\theta_2^2\sin\Delta
\end{aligned}
$$

$$
\begin{aligned}
m_2lr_2\cos\Delta\,\ddot\theta_1
+\left(m_2r_2^2+I_2\right)\ddot\theta_2
&=
- m_2gr_2\sin\theta_2
+ m_2lr_2\,\dot\theta_1^2\sin\Delta
\end{aligned}
$$

---

## 質量行列表示

$$
\begin{bmatrix}
A & B \\
C & D
\end{bmatrix}
\begin{bmatrix}
\ddot\theta_1\\
\ddot\theta_2
\end{bmatrix}
=
\begin{bmatrix}
E\\
F
\end{bmatrix}
$$

ただし
$$
\begin{aligned}
A&=m_1r_1^2+m_2l^2+I_1,\\
B(\theta_1,\theta_2)&=m_2lr_2\cos(\theta_1+\alpha-\theta_2),\\
C(\theta_1,\theta_2)&=m_2lr_2\cos(\theta_1+\alpha-\theta_2),\\
D&=m_2r_2^2+I_2,\\
E(\theta_1,\theta_2,\dot\theta_2)&=-m_1gr_1\sin\theta_1-m_2gl\sin(\theta_1+\alpha)-m_2lr_2\dot\theta_2^2\sin(\theta_1+\alpha-\theta_2),\\
F(\theta_1,\theta_2,\dot\theta_1)&=-m_2gr_2\sin\theta_2+m_2lr_2\dot\theta_1^2\sin(\theta_1+\alpha-\theta_2).
\end{aligned}
$$

---

## (6) クラメルの公式による $\ddot\theta_1,\ddot\theta_2$ の解

$$
A\ddot\theta_1+B\ddot\theta_2=E,\qquad
C\ddot\theta_1+D\ddot\theta_2=F
$$

行列式
$$
\Delta=AD-BC
$$
を用いると，クラメルの公式より
$$
\ddot\theta_1=\frac{ED-BF}{AD-BC},\qquad
\ddot\theta_2=\frac{AF-EC}{AD-BC}.
$$

本系では $B=C$ なので
$$
\Delta=AD-B^2
$$
と簡約される。

---

## (7) 1階連立微分方程式（状態方程式）

状態変数を
$$
x=(\theta_1,\theta_2,\omega_1,\omega_2)
$$
とおく（$\omega_1=\dot\theta_1,\ \omega_2=\dot\theta_2$）。

$$
\begin{cases}
\dot{\theta}_1=\omega_1,\\
\dot{\theta}_2=\omega_2,\\
\dot{\omega}_1=\ddot{\theta}_1=\dfrac{ED-BF}{AD-BC},\\
\dot{\omega}_2=\ddot{\theta}_2=\dfrac{AF-EC}{AD-BC}.
\end{cases}
$$

## コーディングへgo

### モデルについて
↓こちらのモデルを使用

https://free3d.com/ja/3d-model/rigged-male-human-442626.html

このモデルをさらに肘で分割したモデルを利用する。
分割したモデルは↓

https://drive.google.com/drive/folders/1a0eeRAI0kNK-DJDse9i5R2cf44HHlEBL?usp=drive_link

<img src="https://drive.google.com/file/d/18J60TsvP4UgRZ-nFYcs4CTEsCIxBUjZC/view?usp=drive_link" width = 200px>
"""

# ライブラリ
!pip install pyvista numpy-stl
import numpy as np
import matplotlib.pyplot as plt
import pyvista as pv
from stl.mesh import Mesh
from scipy.integrate import solve_ivp

# Driveをマウント
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# パラメーター
inital_state = [
    np.pi/1.5, #theta_1
    np.pi/1.5, #theta_2
    0,       #omega_1
    0        #omega_2
]
density = 1.0
alpha = 0.0
framerate = 30
duration = 60.0
g = 9.8

# モデルの情報を獲得
upper_path = "/content/drive/MyDrive/dualRigidBodyPendulumSim/upper.stl"
lower_path = "/content/drive/MyDrive/dualRigidBodyPendulumSim/lower.stl"
upper_model = Mesh.from_file(upper_path)
lower_model = Mesh.from_file(lower_path)
upper_vol, upper_cog, upper_imat = upper_model.get_mass_properties()
lower_vol, lower_cog, lower_imat = lower_model.get_mass_properties()

r_1, r_2 = float(np.linalg.norm(upper_cog)), float(np.linalg.norm(lower_cog))
m_1, m_2 = float(upper_vol * density), float(lower_vol * density)
I_1, I_2 = float(upper_imat[0, 0]), float(lower_imat[0, 0])
U = np.array([-0.086, 0.024, -0.367])  # upper.stl 内の接続点
L = np.array([ 0.067, 0.337,  0.886])  # lower.stl 内の接続点
l = float(np.linalg.norm(U - O_upper))
print(f"{r_1=}\n{r_2=}\n{m_1=}\n{m_2=}\n{I_1=}\n{I_2=}")

t_span = (0.0, duration)
t_eval = np.linspace(0.0, duration, int(duration * framerate))

A = m_1 * r_1**2 + m_2 * l**2 + I_1
D = m_2 * r_2**2 + I_2

def B(t1, t2):
    return m_2 * l * r_2 * np.cos(t1 + alpha - t2)

def E(t1, t2, o2):
    return (
        -m_1 * g * r_1 * np.sin(t1)
        -m_2 * g * l   * np.sin(t1 + alpha)
        -m_2 * l * r_2 * (o2**2) * np.sin(t1 + alpha - t2)
    )

def F(t1, t2, o1):
    return (
        -m_2 * g * r_2 * np.sin(t2)
        +m_2 * l * r_2 * (o1**2) * np.sin(t1 + alpha - t2)
    )

def eom(t, X):
    t1, t2, o1, o2 = X
    b = B(t1, t2)
    c = b
    e = E(t1, t2, o2)
    f = F(t1, t2, o1)
    den = A * D - b * c
    a1 = (e * D - b * f) / den
    a2 = (A * f - e * c) / den
    return [o1, o2, a1, a2]

sol = solve_ivp(
    eom, t_span, inital_state, t_eval=t_eval,
    rtol=1e-9, atol=1e-9
)

theta1 = sol.y[0]
theta2 = sol.y[1]
omega1 = sol.y[2]
omega2 = sol.y[3]

plt.figure()
plt.plot(sol.t, theta1, label="θ1")
plt.plot(sol.t, theta2, label="θ2")
plt.legend()
plt.xlabel("t[s]")
plt.ylabel("θ[rad]")
plt.show()

plotter = pv.Plotter(notebook=True, window_size=[512, 512])
upper: pv.DataSet = pv.read(upper_path)
lower: pv.DataSet = pv.read(lower_path)
lower.translate(U - L, inplace=True)
plotter.add_mesh(upper)
plotter.add_mesh(lower)
plotter.camera.position = (10, 10, 0)
plotter.camera.focal_point = (0, 0, 0)
plotter.open_movie("result.mp4", framerate=framerate)
t_1_diffs = np.diff(sol.y[0], prepend=[0])
t_2_diffs = np.diff(sol.y[1], prepend=[0])
for (t1, dt1, dt2) in zip(sol.y[0], t_1_diffs, t_2_diffs):
    upper.rotate_x(np.rad2deg(dt1), inplace=True)
    lower.rotate_x(np.rad2deg(dt1), inplace=True)
    ct, st = np.cos(t1), np.sin(t1)
    J = np.array([
        U[0],
        U[1]*ct - U[2]*st,
        U[1]*st + U[2]*ct
    ])
    lower.rotate_x(np.rad2deg(dt2 - dt1), point=tuple(J), inplace=True)
    plotter.write_frame()
plotter.close()

from IPython.display import HTML
from base64 import b64encode

mp4 = open('./result.mp4', 'rb').read()
data_url = 'data:video/mp4;base64,' + b64encode(mp4).decode()
HTML(f"""
<video width="100%" height="100%" controls>
      <source src="{data_url}" type="video/mp4">
</video>""")